# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91e78e2209d0efc3ad32357dab2ca445eccd6cca600628d370afa420b8821caa178d6ee4b3e7b8735a630386f3f1e2ca27db9c223c915fcc0664a9428bda6653

test:
  secret_key_base: 166611a72a7151b553242768ea4f589928b270ac2b61a06bd77c3e65dbf30450227e8a758efa1f218a006f5784104ae73a67a5ff7e0aa3603199655569f3b496

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
